# We divide the EEG segments into five minute intervals according to the Nback division
# and assign the labels to them

# Currently the problem is that we do not know how the labels match up to the segments
# We have EEG recording for variable lengths which are divided into 5 minute segments
# the Nback labels are also generated by 5 minute labeling.
# Now the number of epochs do not line up for quite a few of the cases with Nback being more
# and sometimes EEG being more and rarely equal.
# So if there are no more EEG segments then what?

# Cut the EEG up into 5 minute epochs.  
# Count the EEG epochs
# what is the next step
#I want to make a matrix that contains on the rows, subjects_epochN
# on the columns it should contain EMG features, Class Label from N-back
# So if the EEG is longer than the Nback, something has gone wrong, so I should 
# discard the EEG segment
# If the Nback is longer than the EEG then there is a problem of misalignment.
# So for 1 subject I should look at discarding the first 5 minutes for every EEG anyway
# Then I should subset out the time-series corresponding to every n-back label
# I should write the matrix out with the subjectName_epochN_NbackLabel
# Store this for every subject in one large folder

# Match 1:1, evaluate the length of the labels and EEG divs first and then pick the minimum
# among both, tag them to each other and write out the matrix in a file tagged Name,Epoch,Class


rm(list=ls())
setwd("~/Desktop/StandardWorkflow/")
NbackLabels<-read.table("./InputData/NbackLabels",header = FALSE,sep="\t",stringsAsFactors = FALSE)
rownames(NbackLabels)<-NbackLabels[,1]
NbackLabels<-NbackLabels[,-1]
colnames(NbackLabels)<-NULL

all_files<-list.files(path="./5_ButterworthFiltered/",pattern = "BWFiltered")
subjectNames<-unlist(lapply(strsplit(all_files,split = "_"),function(x){x[1]}))
dir.create(path = "./012_TimeSegmentation")
#i=1
Fs=128;Div_int=5*60

nback_sub_ix<-match(rownames(NbackLabels),subjectNames)

all_files2<-all_files[nback_sub_ix]
nback_subnames<-gsub(all_files2,pattern = "_BWFiltered",replacement = "")  
pb<-txtProgressBar(min=1,max=length(all_files),style = 3)
setTxtProgressBar(pb,i)


is_empty<-function(NbackLabel){
  grep(pattern = "[a-z]",x = NbackLabel)
}

for(i in 1:length(all_files2)){
  
  df<-read.table(file=paste("./5_ButterworthFiltered/",all_files2[i],sep=""), header=TRUE,sep=",",stringsAsFactors=FALSE)
  Div_ix<-seq(from = (Fs * Div_int),to = nrow(df),by = Fs * Div_int) #skip first 5 minutes
  
  label_len<-length(is_empty(NbackLabels[i,]))
  EEG_seg_len<-(length(Div_ix)-1)
  nback_eeg_lengths<-c(label_len,EEG_seg_len)
  min_len<-which.min(nback_eeg_lengths)
  ix_limit<-nback_eeg_lengths[min_len]
  
  for(j in 1:ix_limit) #skip 1st epoch for EEG
  {
  epoch_cut<-df[c(Div_ix[j]:Div_ix[j+1]),]
  Nback_eventLabel<-unlist(NbackLabels[i,(j)])
  file_names<-paste(nback_subnames[i],j,Nback_eventLabel,sep="_")
  paste("./012_TimeSegmentation/",file_names,".csv",sep = "")
  write.table(x = epoch_cut,file = paste("./012_TimeSegmentation/",file_names,sep = ""),quote = FALSE,sep = ",",row.names = FALSE,col.names = TRUE)
  }
}

#----------------------------------------------------------------------------  
